from selenium.webdriver.common.by import By
from .data import *


Login_panel = (By.XPATH, "//*[contains(@class, 'logSprite icClose')]")
save_ad = (By.XPATH, "//*[contains(@class, 'sc-jlwm9r-1 ewETUe')]")
deny_btn = (By.ID,'deny')
iframe_id = (By.ID, "webpush-onsite")
Train_select = (By.XPATH, "//*[text()='Trains' and @class = 'sc-1f95z5i-4 drxYQA']")
source_select = (By.XPATH, "//*[contains(@class, 'styles_FswFldHeading__5ZTwg') and text() = 'From']")
source_station = (By.XPATH, "//*[contains(@class, 'styles_FswAutoCompLegend___EW1V')]//following-sibling::input")
source_stn_select = (By.XPATH, f"//p[contains(@class, 'styles_FswAutoCompItemDescTitle__cEIX6') and text()='{source_city}']")
dest_select = (By.XPATH, "//*[contains(@class, 'styles_FswFldTitle__0nABI') and contains(text() , 'Destination')]")
dest_station = (By.XPATH, "//*[contains(@class,'styles_FswAutoComp__xECf3')]//child::input")
dest_stn_select = (By.XPATH, f"//p[contains(@class, 'styles_FswAutoCompItemDescTitle__cEIX6') and text()='{dest_city}']")
journey_date = (By.XPATH, f"//p[contains(text(), '{mmyy}')]//parent::div//parent::div//p[text()='{dd}']")
search_train = (By.XPATH, "//span[text()='SEARCH TRAINS']")
sort_dropdown = (By.XPATH, "//span[text()='Popularity']//ancestor::div[contains(@class,'makeRelative')]")
sort_select = (By.XPATH, f"//*[text() = '{sort_type}']//parent::p[contains(text(), '{sort_by}')]")
trainclass_select = (By.XPATH, f"//p[text() = '12608']//parent::div//parent::div//parent::div//p[text() = '2S']")
irctc_username = (By.CSS_SELECTOR, "#IRCTC_Username")
validate_irctc = (By.XPATH, "//p[text()='VALIDATE & SAVE ']")
add_passenger = (By.XPATH, "//p[text()='ADD NEW TRAVELLER']")
add_another_passenger = (By.XPATH, "//p[text()='+ Add New Traveller']")
passenger_name = (By.CSS_SELECTOR, "#user_name")
passenger_age = (By.CSS_SELECTOR, "#user_age")
berth_preference = (By.CSS_SELECTOR, "#Berth_Preference")
save_passenger = (By.XPATH,"//p[text()='Save']")
refund_cancel = (By.XPATH, "//input[contains(@id, 'getRefund_No')]//parent::span//p")
contact_number = (By.CSS_SELECTOR, "#contact_no")
contact_mail = (By.CSS_SELECTOR, "#contact_mail_id")
payment_button = (By.XPATH, "//p[text() = 'Proceed to Payment']")
page_bottom = (By.XPATH, "//p[contains(text(), 'GSTIN')]")
add_preference = (By.XPATH, "//p[text()='Additional preferences']//parent::div")
auto_upgrade = (By.XPATH, "//p[contains(text(), 'auto upgradation')]//parent::label")
book_only = (By.XPATH, "//p[contains(text(), 'Book only if confirm')]//parent::label")
book_choice = (By.XPATH, "//input[contains(@id, 'BookOnlyIf')]//parent::div")
same_coach = (By.XPATH, "//p[contains(text(), 'berths are allotted in same coach')]//parent::li")