from selenium.webdriver.common.by import By
from .Goibibo_data import *

Login_close = (By.XPATH, '//*[contains(@class, "logSprite icClose")]')
discount_ad = (By.XPATH, '//*[contains(@class, "sc-jlwm9r-1 ewETUe")]')
iframe_element = (By.XPATH, "//iframe[@name = 'webpush-onsite']")
notification_deny = (By.XPATH, '//*[@id= "deny"]')
from_btn = (By.XPATH, '//*[text()="From"]//following-sibling::*[contains(@class, "sc-12foipm-6 erPfRs")]')
from_city_loc = (By.XPATH, '//*[text()="From"]//following-sibling::*[contains(@type, "text")]')
to_city_loc = (By.XPATH, '//*[text()="To"]//following-sibling::*[contains(@type, "text")]')
departure = (By.XPATH, '//*[text()="Departure"]//parent::div//span[contains(@class,"sc-12foipm-8 eXKWBG fswDownArrow")]')
depart_date_loc = (By.XPATH, f'//*[contains(@aria-label,"{depart_date}")]')
next_month = (By.XPATH, '// *[contains(@aria-label, "Next Month")]')
return_cell = (By.XPATH, '//*[text()="Return"]//parent::div//p')
return_cal = (By.XPATH, '//*[text()="Return"]//parent::div//span[contains(@class,"sc-12foipm-8 eXKWBG fswDownArrow")]')
return_date_loc = (By.XPATH, f"//*[contains(@aria-label,'{return_date}')]")
Travellers = (By.XPATH, "//*[contains(text(), 'Travellers')]")
Adult_count = (By.XPATH,"//*[text()='Adults']//parent::div//span[3]")
Child_count = (By.XPATH,"//*[text()='Children']//parent::div//span[3]")
Infant_count = (By.XPATH,"//*[text()='Infants']//parent::div//span[3]")
done_btn = (By.XPATH, "//a[text()='Done']")
search_flight = (By.XPATH, "//*[text()='SEARCH FLIGHTS']")